# Generated by Django 3.1.5 on 2023-12-07 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dep_ID', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Department_ID')),
                ('Dep_Name', models.CharField(max_length=20, unique=True, verbose_name='Department_Name')),
                ('Manager', models.CharField(max_length=40, verbose_name='Manager_Name')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Code', models.IntegerField(primary_key=True, serialize=False, verbose_name='JobId')),
                ('Post', models.CharField(max_length=20, verbose_name='Job Post')),
                ('HRA', models.IntegerField(verbose_name='HRA')),
                ('TA', models.IntegerField(verbose_name='TA')),
                ('DA', models.IntegerField(verbose_name='DA')),
                ('PF', models.IntegerField(verbose_name='PF')),
                ('IT', models.IntegerField(verbose_name='IT')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=35, verbose_name='Name')),
                ('DOB', models.DateField(verbose_name='Date_of_Birth')),
                ('Address', models.CharField(max_length=60, verbose_name='Address')),
                ('Contact', models.IntegerField(verbose_name='Contact_No')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email_id')),
                ('Basic_Salary', models.IntegerField(verbose_name='Basic')),
                ('DOJ', models.DateField(verbose_name='Date_Of_Joining')),
                ('Dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.department')),
                ('Job_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.job')),
            ],
        ),
    ]
