# Generated by Django 3.1.5 on 2023-12-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dep2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_ID', models.CharField(max_length=5, verbose_name='Department_ID')),
                ('Dep_Name', models.CharField(max_length=20, unique=True, verbose_name='Department_Name')),
                ('Manager', models.CharField(max_length=40, verbose_name='Manager_Name')),
            ],
        ),
    ]
