# Generated by Django 3.1.5 on 2023-12-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_dep2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dep2',
        ),
    ]
