# Generated by Django 3.1.5 on 2023-12-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20231210_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFReport',
            fields=[
                ('Sno', models.IntegerField(primary_key=True, serialize=False, verbose_name='Sno')),
                ('Accno', models.IntegerField(verbose_name='Account No')),
                ('IFSC', models.CharField(max_length=12, verbose_name='IFSC Code')),
                ('Bank_Name', models.CharField(max_length=30, verbose_name='Bank Name')),
                ('PFAmount', models.IntegerField(verbose_name='PFAmount')),
            ],
        ),
        migrations.AddField(
            model_name='bank_details',
            name='Bank_Name',
            field=models.CharField(default='NULL', max_length=30, verbose_name='Bank Name'),
        ),
    ]
