# Generated by Django 3.1.5 on 2023-12-12 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20231212_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfreport',
            name='Date',
            field=models.DateField(default=datetime.datetime(2023, 12, 12, 6, 29, 50, 235140, tzinfo=utc), verbose_name='Date'),
            preserve_default=False,
        ),
    ]
