# Generated by Django 3.1.5 on 2023-12-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_pfreport_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='Basic',
            new_name='Salary',
        ),
    ]
