# Generated by Django 3.1.5 on 2023-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20231213_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Basic_Salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(default=100000, verbose_name='Total Salary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Salary',
            field=models.IntegerField(verbose_name='Total Salary'),
        ),
    ]
